### PR TITLE
fix: NAN_MODULE_WORKER_ENABLED

### PR DESCRIPTION
**Pull request by achille-roussel**
Fixes https://github.com/astro/node-expat/issues/203

I followed the recommended fix from https://github.com/nodejs/nan/issues/844 which appears to address the issue in the reported test case and other programs I tested it in.

Let me know if you wish to see something changed.

### CODE REVIEW

**Comment by achille-roussel** [comment]
Any updates?

**Comment by achille-roussel** [comment]
Hello, would you have any updates to share on this issue?

**Comment by Y--** [comment]
Sorry for the late follow-up. Could you add a test for this?

**Comment by Prinzhorn** [comment]
Making a module context aware _might_ require cleanup using `node::AddEnvironmentCleanupHook`. An example can be seen here: https://github.com/CharlieHess/node-mac-notifier/pull/32/files
I just want to make sure if this lands it will work properly.

**Comment by achille-roussel** [comment]
Hey, I have not needed this change (maintained a fork at first, but did not need it anymore either), so I probably won't be finishing this PR.

Thanks for the replies, hopefully it will be useful if someone else runs into a similar issue.

**Comment by XDean** [comment]
@achille-roussel  Why you don't need this change, did you find any workaround? I'm now suffering from the same issue.

**Comment by achille-roussel** [comment]
We stopped using worker threads in our code so the limitation didn't apply to our case anymore.

**Comment by XDean** [comment]
> We stopped using worker threads in our code so the limitation didn't apply to our case anymore. 

So how do you deal with long time work?  Now I need the process some large xml files. If I don't use workers threads, How to avoid it block mian thread?

**Pull request closed without merging**
