### PR TITLE
Update for Node 12

### PR DESCRIPTION
**Pull request by Y--**

### CODE REVIEW

**Comment by tomkel** [comment]
@astro

**Comment by gajus** [comment]
Published https://www.npmjs.com/package/xml2json-temporary as a temporary workaround.

**Comment by herbrandson** [comment]
@astro would you mind chiming in and letting us know if this is something you're planning on getting to or if this is a repo that is no longer being maintained?

**Comment by tomkel** [comment]
I tried emailing him, but no response.

**Comment by gajus** [comment]
I suggest contact NPM support and saying that the author is unresponsive. If the author does not respond within 14 days, the package will be handed over to whoever requests to takeover the namespace. I would also include reference to this issue.

**Comment by Y--** [comment]
I just sent an e-mail to NPM's support team, will let you know here what they suggest.

**Comment by astro** [comment]
Hi

It's great that this code is broadly used and that people try to contribute. It has been only a week since @tomkel reached out and his e-mail address bounced. Please be a bit more patient. :)

Is there anyone else who would like to share the joy of reviewing PRs and helping @tomkel with the release process?

**Comment by Y--** [comment]
Hi @astro!

I'm happy to be a contributor and review PRs if/when need be.
Feel free to contact me directly if you want to discuss it more :-)

Thanks,

Y.

**Comment by Y--** [comment]
Thanks again @astro for allowing me to contribute to this project.
As you all might already have seen by now, I've merged this PR and released 2.3.18 that contains these changes. Let me know if I've missed anything. Thanks!

**Pull request merged**
